resources:
  - ../../base
images:
  - name: pim-backend-api
    newTag: dev2
patches:
  - target:
      kind: Deployment
      name: pim-backend-api
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: pim-backend-api
      spec:
        replicas: 1
