---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: pim-backend-db-url
  namespace: pim
spec:
  encryptedData:
    DATABASE_URL: AgAFAmC/2RRc6WUdqWBBA4NTBT9NT9vBu8N1uSFD2ct5cGZkaWmEVcA8SkiuTi9xARvNsBchXCwNKfNIs/AjSpd9LEXv9pWUlEXO+jVJ11DhS6++4xoo0hkcsqnXIKy/X9a/cq9Scu/wz37gQxEBKzukvg7kPg5gjxmf4VnaNUBjXrb77PbTRaBVq/vUCmdjkH6N4LV8STBC9eqO8SR7upKFJFPLvQFfHPM3FbA5q6Mtjn10MKdcbzdf2iWcVQOnChARkoPBML0RAQZ9Oiep1Ly1R8lkfRcev1Pz3qs62SA5mM5Z3euiFscCJb7ex513wIeTY50Rs5esdPkzLGGWTdrzYCZBe9VCNu1/eFbQe5fN//GACNfhEqCeb7yX3cdyK+XvChgV9FzxnzMoOlxUg+WMGNsWAMyuosDqR0fpxb8WF8tRxvtsNUSd1t7jIdXb/nJPDPnqw2381lscSWeW5XcvtV16PvqQea46RVMEqoz5ETNw7SNbbW3xkZjaWQswsMUY+L6ZVE0s7LvydPnNJjul9AjkJ/pGakbMtDntVAJPL14RFD2AvTpNwdMM78RkbGhsS3bDpT4vjJtB0p5M9aor4CCziDyhZpyuw3v7fZV42upTeQFbXyUhs/kRNA8AnXiJeVaPjbewyZnWCAEgVES0UrpuikG40bLyM2deqAzv79CrKi7ZtblPuRQmNoQPEGNd2ZgEX7wYzDpVLDDMqo7zaSd01fTfc2Y7fWCRZzbWLz8e4Zcx+6CVTV8Id1spiyhXXBCVf5l+GahmnkEvbH6mdZFZKGi1Scnvkk5PqMMFL1wyG+cpYwJC
  template:
    metadata:
      name: pim-backend-db-url
      namespace: pim
