apiVersion: v1
kind: Secret
metadata:
  name: pim-backend-db-url
  namespace: pim
  labels:
    app: pim-backend-api
stringData:
  DATABASE_URL: postgresql://root@cockroachdb-public.crdb.svc.cluster.local:26257/app_db?sslmode=disable
